[package]
name = "smolmatrix"
version = "0.1.5"
edition = "2021"
description = "Small simple matrix library"
license = "BSD-2-Clause-Patent"
repository = "https://github.com/funnsam/smolmatrix"

[dependencies]

[features]
default = ["std"]
std = []
